title: Tailwind Jekyll Starter Kit (Internal Style Version)
description: A starter kit for using Tailwind with Jekyll (internal style version)

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.js
